project:
  type: website
  output-dir: ./docs

website:
  title: "RIBBiTR Data Access Center"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "RIBBiTR Database Tutorial Series"
        href: tutorial_series/00_tutorial_series.qmd
        contents:
          - ./tutorial_series/01_connection_setup.qmd
          - ./tutorial_series/02_data_discovery.qmd
          - ./tutorial_series/03_data_pulling.qmd
          - ./tutorial_series/04_data_workflow.qmd
      - section: "Database updates"
        contents: 
          - text: "Schema Diagram: survey_data"
            href: schema_diagram_survey_data.png
          - text: "Database Changelog"
            href: db_changelog.md
      - section: "Presentations"
        contents: 
          - text: "Database in Context"
            href: ./presentations/db_context_presentation.html
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

