project:
  type: website
  output-dir: ./docs

website:
  title: "RIBBiTR Data Access"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "RIBBiTR Database Tutorial Series"
        href: tutorial_series/00_tutorial_series.qmd
        contents:
          - ./tutorial_series/01_connection_setup.qmd
          - ./tutorial_series/02_data_discovery.qmd
          - ./tutorial_series/03_data_pulling.qmd
          - ./tutorial_series/04_table_joins.qmd
          - ./tutorial_series/05_bd_capture_workflow.qmd
          - ./tutorial_series/06_microclimate_workflow.qmd
          - ./tutorial_series/07_database_refresher.qmd
      - section: "Database Resources"
        contents: 
          - section: "Schema Diagrams"
            contents:
              - text: "microclimate_data"
                href: ./resources/schema_diagram_microclimate_data.png
              - text: "survey_data"
                href: ./resources/schema_diagram_survey_data.png
          - text: "Database Changelog"
            href: ./resources/db_changelog.md
          - text: "RIBBiTR Github"
            href: https://github.com/RIBBiTR-BII
      - section: "Presentations"
        contents: 
          - text: "Database in Context"
            href: ./presentations/db_context_presentation.html
          - text: "Database Refresher 2025"
            href: ./presentations/db_updates_2025-04.html
            

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

