---
title: "RIBBiTR Data Access Center"
---

This is a repository for organizing and hosting data access resources within the [RIBBiTR](https://ribbitr.com/) project. Our team at RIBBiTR is dedicated to advancing an understanding of resilience by developing, applying, and sharing a novel framework for the study of resilience. As an interdisciplinary and cross-scale research project, RIBBiTR's goals require open collaboration and communication within our team, which these resources are designed to facilitate.


## Getting started
To begin, take a look at the resources provided in the menu to the left!

## Closing the loop
Data access is an important component of our collaborative effort within RIBBiTR, but it does not exist in a vacuum. Sharing of data is enhanced when coupled with other forms of high-context communication, such as interpersonal dialogue, collaborative writing and messaging, code sharing, and more. Confused by the data? See something odd? Encounter a barrier? help us increase the context in our communication by reaching out within the team for a conversation!

Any questions? Reach out to the [RIBBiTR data manager](mailto:jstaines@ucsb.edu).

**_This website and its contents were created in R using [Quatro](https://quarto.org/). Source files are [available on Github](https://github.com/RIBBiTR-BII/ribbitr-data-access) under a [GPL v3 license](https://github.com/RIBBiTR-BII/ribbitr-data-access/blob/main/LICENSE)._**

[RIBBiTR](https://ribbitr.com/) is a [Biology Integration Institute](https://www.nsf.gov/funding/opportunities/bii-biology-integration-institutes/), funded by the [National Science Foundation](https://www.nsf.gov/).
